Remove the use of deprecated pandas DataFrame.append() method
lit26/finvizfinance pull request #56
Opened 2022-06-07 01:46 UTC by lucasmlofaro

## Description

Resolves #55 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Code styling or code optimize

## What you did

Refactor calls to `df.append()` to use `pd.concat()` instead. To make this work, I have also delayed the creation of the `DataFrame` until after the loops are complete. This should be more efficient as well.

2022-06-11 04:08 UTC, lit26 requested changes

2022-06-11 04:08 UTC, lit26 commented on finvizfinance/calendar.py
>          ]
Please remove the unused columns

2022-06-13 16:36 UTC, lucasmlofaro commented on finvizfinance/calendar.py
>          ]
Good catch

2022-06-14 05:45 UTC, lit26 approved these changes
Your PR is approved. Thanks for your contribution.

2022-06-14 05:45 UTC, merged