added page_count attribute in overview class
lit26/finvizfinance pull request #79
Opened 2023-06-29 20:00 UTC by aliziauddin

## Page Count attribute in screener overview class

### Summary

In this PR i've just added page count attribute, so that i can access that value.

### Type of Change
- [x] New feature (non-breaking change which adds functionality)

No new dependencies are required for this change.

2023-06-30 20:36 UTC, aliziauddin commented
@lit26 can you please review this, if everything is fine then please merge this, as I need this update asap.
thanks.

2023-07-02 04:23 UTC, lit26 requested changes

2023-07-02 04:23 UTC, lit26 commented on finvizfinance/screener/overview.py
> +        self.page_count = 0
Set this to None

2023-07-02 04:23 UTC, lit26 commented on finvizfinance/screener/overview.py
> +            self.page_count = page_count
Combine the above and return self.page_count

2023-07-02 05:22 UTC, merged